### ISSUE TITLE
The bubb needs to adjusted to be shown at the top if the repeated item is at the bottom of the page. 

### ISSUE THREAD

**Issue by jithureddy** [frdnrdb/bubb#2]
Hi,

I have list of items and keep the bubb direction as default south. So for the bottom one I cannot see the tooltip.
It would be better if the tooltip auto adjust based on the screen.

**Comment by frdnrdb** [comment]
first; i kind of published then forgot about this whole project, so i'd like to apologize for the significant absence :-)

originally i wanted this to be "non-fancy", so i considered then dropped the idea of implementing screen-edge-aware direction. 

but, since you asaked: **added config option for 'autoDirection' in the latest version** - per bubb or globally
